name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'

      - name: Setup turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        env:
          NUXT_APP_BASE_URL: /font-comparer/
        run: pnpm exec turbo run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'

      - name: Setup turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm exec turbo run lint

  deploy:
    needs: [build, lint]
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
